[project]
name = "diapostesis"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "gaanim",
]

[tool.pyright]
include = ["src", "main.py"]
extraPaths = ["src"]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
pythonVersion = "3.14"
reportUnusedCallResult = false
reportImplicitStringConcatenation = false

[tool.uv.sources]
gaanim = { path = "C:/Tools/gaanim/gaanim-0.7.2-py3-none-any.whl" }
